# leads comments in a line 
# Build all: default target
all : demo

#specify the compiler
CC = gcc  #this is the GUN C++ complier

#specify the compiler options
CFLAGS = -ggdb

# Separate compilation to build object files
main.o : main.c functions.h 
	$(CC) -c $(CFLAGS) main.c

functions.o : functions.c functions.h 
	$(CC) -c $(CFLAGS) functions.c

# linking
#demo is a target which depends upon main.o and functions.o 
#"gcc main.o functions.o -o demo" is the command to produce the executable file
#You need to use a TAB before gcc 
demo : main.o functions.o
	$(CC) main.o functions.o -o demo

# Testing
check : all
	./demo

# Clean up all build targets so that one may get a clean build
clean :
	rm -f *.o demo core.*
													
